version: '3.8'

x-nginx-cmn: &nginx-cmn
  image: nginx:alpine
  networks:
    - app-network

services:
  srv:
    build:
      context: ./srv
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./srv:/var/www/html/
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network
      
  nginx-srv:
    <<: *nginx-cmn
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./srv:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - srv

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    stdin_open: true
    tty: true

  nginx-web:
    <<: *nginx-cmn
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app
      - ./web/dist:/usr/share/nginx/html
    ports:
      - "90:90"
    depends_on:
      - web

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
